name: CI
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-and-push-docker-image:
    name: Build and push docker image
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build . --file ./Dockerfile --tag appbrewhouse/lodgercontrol-backend
      - run: docker push appbrewhouse/lodgercontrol-backend
  build-ami:
    name: Build AMI image
    env:
      PKR_VAR_docker_username: ${{ secrets.DOCKER_USERNAME }}
      PKR_VAR_docker_password: ${{ secrets.DOCKER_PASSWORD }}
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - run: bash .deploy/scripts/packer-install.sh
      - run: cd .deploy/packer && packer validate image.pkr.hcl
      - name: build ami image
        run: cd .deploy/packer && packer build image.pkr.hcl
